pipeline {
    agent any

    stages{
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/s225255856/8.1CDevSecOps.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'npm test || true' //allows pipeline to continue despite test failures
            }
        }
        stage('Generate Coverage Report') {
            steps {
                //ensure coverage report exist
                sh 'npm run coverage || true'
            }
        }
        stage('NPM Audit (Security Scan)') {
            steps {
                sh 'npm audit || true' //this will show known CVEs in the output
            }
        }
    }
}