pipeline {
    agent any

    stages{
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/s225255856/8.1CDevSecOps.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                bat 'npm test || exit /b 0' //allows pipeline to continue despite test failures
            }
        }
        stage('Generate Coverage Report') {
            steps {
                //ensure coverage report exist
                bat 'npm run coverage || exit /b 0'
            }
        }
        stage('NPM Audit (Security Scan)') {
            steps {
                bat 'npm audit || exit /b 0' //this will show known CVEs in the output
            }
        }
    }
}